Repository Mashiepotatoes/Gambly, pull requests merged in 2021-09, with the labels that each got.

#1 feat: add pull request template
  .github/pull_request_template.md:Zone.Identifier
Labels: enhancement

#2 users model and validation done
  Gemfile
  Gemfile.lock
  app/models/user.rb
  config/environments/development.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20210914054701_devise_create_users.rb
  db/migrate/20210914061305_addusernamecolumn.rb
  db/schema.rb
  test/models/user_test.rb
Labels: enhancement

#3 experience and review model
  app/models/experience.rb
  app/models/review.rb
  app/models/user.rb
  db/migrate/20210914065859_create_reviews.rb
  db/migrate/20210914070436_create_experiences.rb
  db/schema.rb
  test/models/experience_test.rb
  test/models/review_test.rb
Labels: enhancement

#4 feat: user experience and favorite model creation
  Gemfile.lock
  app/models/favorite.rb
  app/models/userexperience.rb
  db/migrate/20210914075307_create_favorites.rb
  db/migrate/20210914075919_create_userexperiences.rb
  db/schema.rb
  test/models/favorite_test.rb
  test/models/userexperience_test.rb
Labels: enhancement

#5 feat: create question and answer models
  .vscode/extensions.json
  app/models/answer.rb
  app/models/question.rb
  db/migrate/20210914075853_create_questions.rb
  db/migrate/20210914075936_create_answers.rb
  db/schema.rb
  test/models/answer_test.rb
  test/models/question_test.rb
Labels: enhancement

#6 devise routes working!
  app/models/experience.rb
  app/models/user.rb
  config/routes.rb
  db/schema.rb
Labels: enhancement

#7 Add username to devise
  app/assets/images/logo.png
  app/controllers/application_controller.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_navbar.html.erb
Labels: enhancement

#8 change authentication key to username,session input field
  app/models/user.rb
  app/views/devise/sessions/new.html.erb
  config/initializers/devise.rb
Labels: enhancement

#9 seed faker
  .vscode/extensions.json
  Gemfile
  Gemfile.lock
  db/migrate/20210915035312_add_photo_url_to_experience.rb
  db/schema.rb
  db/seeds.rb
Labels: enhancement

#10 Experience list show
  app/controllers/application_controller.rb
  app/controllers/experiences_controller.rb
  app/models/experience.rb
  app/models/user.rb
  app/views/experiences/show.html.erb
  config/routes.rb
  test/controllers/experiences_controller_test.rb
Labels: enhancement

#12 Experience show view wireframe
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_card_trip.scss
  app/models/experience.rb
  app/views/experiences/show.html.erb
  db/seeds.rb
Labels: enhancement

#11 landing javascript
  app/assets/images/scott-trento-mUFFI4CkmAI-unsplash.jpg
  app/assets/stylesheets/components/_background.scss
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_searchBar.scss
  app/controllers/experiences_controller.rb
  app/views/experiences/index.html.erb
  app/views/pages/home.html.erb
  db/seeds.rb
Labels: enhancement

#13 card-component
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/components/_experience.scss
  app/assets/stylesheets/components/_index.scss
  app/views/experiences/index.html.erb
  app/views/pages/home.html.erb
Labels: enhancement

#14 Payments route controller
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_cart.scss
  app/controllers/checkout_controller.rb
  app/controllers/experiences_controller.rb
  app/views/checkout/index.html.erb
  app/views/experiences/show.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
  test/controllers/checkout_controller_test.rb
Labels: enhancement

#15 logo changed
  app/assets/images/GAMBLY(5).png
  app/assets/stylesheets/components/_navbar.scss
  app/views/devise/sessions/new.html.erb
  app/views/experiences/index.html.erb
  app/views/shared/_navbar.html.erb
Labels: enhancement

#16 Landing page css
  app/assets/images/logo-white.png
  app/assets/images/logo.png
  app/assets/stylesheets/pages/_home.scss
  app/controllers/application_controller.rb
  app/views/layouts/application.html.erb
  app/views/pages/home.html.erb
Labels: enhancement

#17 prettify login page & navbar
  app/assets/images/logo-yellow.png
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_background.scss
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/config/_bootstrap_variables.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/pages/_index.scss
  app/views/devise/sessions/new.html.erb
  app/views/shared/_navbar.html.erb
Labels: enhancement

#18 Amendments to Home and Index pages
  app/assets/images/logo-white.png
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_background.scss
  app/assets/stylesheets/components/_banner.scss
  app/assets/stylesheets/components/_searchBar.scss
  app/assets/stylesheets/pages/_home.scss
  app/assets/stylesheets/pages/_index.scss
  app/views/experiences/index.html.erb
  app/views/layouts/application.html.erb
  app/views/pages/home.html.erb
Labels: enhancement

#19 sign up form styling
  app/assets/stylesheets/components/_landing.scss
  app/assets/stylesheets/pages/_sign_up.scss
  app/views/devise/registrations/new.html.erb
Labels: enhancement

#20 Feat: improve search bar function
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/components/_searchBar.scss
  app/controllers/experiences_controller.rb
  app/models/experience.rb
  app/views/layouts/application.html.erb
Labels: enhancement

#22 Gambly function and landing page buttons
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_card_trip.scss
  app/assets/stylesheets/components/_searchBar.scss
  app/assets/stylesheets/pages/_home.scss
  app/assets/stylesheets/pages/_index.scss
  app/assets/stylesheets/pages/_sample.scss
  app/controllers/experiences_controller.rb
  app/views/experiences/sample.html.erb
  app/views/pages/home.html.erb
  config/routes.rb
Labels: enhancement

#21 Feat favorites
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/components/_card_trip.scss
  app/controllers/favorites_controller.rb
  app/javascript/packs/application.js
  app/javascript/plugins/init_favorites.js
  app/models/favorite.rb
  app/models/user.rb
  app/views/experiences/index.html.erb
  app/views/experiences/show.html.erb
  app/views/favorites/create.html.erb
  app/views/favorites/index.html.erb
  app/views/favorites/new.html.erb
  app/views/layouts/application.html.erb
  app/views/pages/home.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
  test/controllers/favorites_controller_test.rb
Labels: enhancement

#23 added seeds, edited index.scss, updated index & show views
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_card_trip.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/config/_bootstrap_variables.scss
  app/assets/stylesheets/pages/_experience_show.scss
  app/assets/stylesheets/pages/_index.scss
  app/assets/stylesheets/pages/_sign_up.scss
  app/views/devise/registrations/new.html.erb
  app/views/experiences/index.html.erb
  app/views/experiences/show.html.erb
  db/seeds.rb
Labels: enhancement

#24 Stripe payment feature
  Gemfile
  Gemfile.lock
  app/controllers/checkout_controller.rb
  app/controllers/orders_controller.rb
  app/controllers/payments_controller.rb
  app/models/order.rb
  app/models/user.rb
  app/services/stripe_checkout_session_service.rb
  app/views/experiences/show.html.erb
  app/views/order/show.html.erb
  app/views/payments/new.html.erb
  config/initializers/stripe.rb
  config/routes.rb
  db/migrate/20210916040756_create_orders.rb
  db/migrate/20210916061711_remove_sku_from_order.rb
  db/migrate/20210916063040_edit_price_column_of_order.rb
  db/schema.rb
  server.rb
  test/controllers/payments_controller_test.rb
  test/models/order_test.rb
Labels: enhancement

#27 Add rating and location parameters
  db/migrate/20210916113041_add_rating_and_location_to_experiences.rb
  db/schema.rb
  db/seeds.rb
Labels: enhancement

#28 Feat filter by location
  app/controllers/experiences_controller.rb
  app/views/experiences/index.html.erb
Labels: enhancement

#29 modify home page search bar
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/components/_searchBar.scss
  app/assets/stylesheets/pages/_home.scss
  app/assets/stylesheets/pages/_sign_up.scss
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/pages/home.html.erb
Labels: enhancement

#30 fix gambly link, fix location filter dropdown
  app/views/experiences/index.html.erb
  app/views/pages/home.html.erb
Labels: bug

#31 Fix favorites
  app/controllers/experiences_controller.rb
  app/controllers/favorites_controller.rb
  app/javascript/packs/application.js
  app/javascript/plugins/init_favorites.js
  app/models/user.rb
  app/views/experiences/show.html.erb
  config/routes.rb
Labels: bug

#34 fix homepage navbar button issues
  app/assets/stylesheets/components/_background.scss
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/pages/_home.scss
  app/views/layouts/application.html.erb
  app/views/layouts/landing_page.html.erb
  app/views/pages/home.html.erb
Labels: enhancement

#36 Feat shopping cart
  app/controllers/favorites_controller.rb
  app/javascript/packs/application.js
  app/javascript/plugins/init_Modal.js
  app/views/experiences/show.html.erb
  db/migrate/20210917072340_add_details_to_orders.rb
  db/schema.rb
  package.json
  yarn.lock
Labels: enhancement

#37 Reviews ratings
  app/controllers/reviews_controller.rb
  app/models/experience.rb
  app/models/rating.rb
  app/models/review.rb
  app/views/experiences/show.html.erb
  app/views/reviews/create.html.erb
  app/views/reviews/new.html.erb
  config/routes.rb
  db/migrate/20210917091941_create_ratings.rb
  db/migrate/20210917092126_add_reference_to_rating.rb
  db/migrate/20210917092149_add_reference_to_review.rb
  db/schema.rb
  test/controllers/reviews_controller_test.rb
  test/models/rating_test.rb
Labels: enhancement

#39 update schema
  db/schema.rb
Labels: bug

#41 Review feature
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_experience.scss
  app/views/experiences/show.html.erb
Labels: enhancement

#40 Sticky navbar
  app/assets/stylesheets/components/_banner.scss
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_landing.scss
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/components/_searchBar.scss
  app/assets/stylesheets/pages/_home.scss
  app/assets/stylesheets/pages/_sign_up.scss
  app/views/experiences/index.html.erb
  app/views/layouts/landing_page.html.erb
  app/views/shared/_navbar.html.erb
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement

#42 Feat shopping cart 2
  app/controllers/cart_controller.rb
  app/javascript/packs/application.js
  app/javascript/plugins/init_Cart.js
  app/javascript/plugins/init_Modal.js
  app/views/cart/show.html.erb
  app/views/experiences/show.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
  test/controllers/cart_controller_test.rb
Labels: enhancement

#44 Carousel index page
  Gemfile
  Gemfile.lock
  app/assets/images/arpad-czapp-mnrok9qT_mk-unsplash (1).jpg
  app/assets/images/igor-starkov-EMeGuuE3DLg-unsplash.jpg
  app/assets/images/kayak.jpg
  app/assets/images/orchard.jpg
  app/assets/images/roberto-nickson-qxD1jo7KW70-unsplash.jpg
  app/assets/images/theme_park.jpg
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_banner.scss
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/pages/_experience_show.scss
  app/assets/stylesheets/pages/_experiences.scss
  app/assets/stylesheets/pages/_index.scss
  app/assets/stylesheets/pages/_login.scss
  app/assets/stylesheets/pages/_sign_up.scss
  app/javascript/packs/application.js
  app/javascript/styles/application.scss
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/experiences/index.html.erb
  app/views/layouts/landing_page.html.erb
  app/views/pages/home.html.erb
  app/views/shared/_navbar.html.erb
  package.json
  yarn.lock
Labels: enhancement

#45 Add search to navbar
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/components/_searchBar.scss
  app/assets/stylesheets/pages/_experiences.scss
  app/views/experiences/index.html.erb
  app/views/pages/home.html.erb
  app/views/shared/_navbar.html.erb
  yarn.lock
Labels: enhancement

#46 resize sign up page
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/pages/_sign_up.scss
  app/views/devise/registrations/new.html.erb
  app/views/layouts/landing_page.html.erb
Labels: enhancement

#49 Fix review by user
  app/controllers/reviews_controller.rb
  app/views/experiences/show.html.erb
  db/schema.rb
Labels: bug

#50 add t&c & some styling
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_card_trip.scss
  app/assets/stylesheets/components/_experience.scss
  app/assets/stylesheets/components/_icon.scss
  app/assets/stylesheets/components/_index.scss
  app/views/experiences/show.html.erb
Labels: enhancement

#51 Feat shopping cart 4
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_cart.scss
  app/controllers/cart_controller.rb
  app/javascript/plugins/init_Cart.js
  app/javascript/plugins/init_Modal.js
  app/views/cart/show.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
  db/seeds.rb
Labels: enhancement

#52 experience card styling
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/components/_experience.scss
  app/views/experiences/index.html.erb
Labels: enhancement

#54 seed file
  db/seeds.rb
Labels: enhancement

#55 Index, filter, and results pages styling
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_banner.scss
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/components/_icon.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_search_bar.scss
  app/assets/stylesheets/config/_fonts.scss
  app/assets/stylesheets/pages/_experiences.scss
  app/assets/stylesheets/pages/_sample.scss
  app/views/experiences/filter.html.erb
  app/views/experiences/index.html.erb
  app/views/experiences/results.html.erb
  app/views/experiences/sample.html.erb
  app/views/pages/home.html.erb
  db/schema.rb
Labels: bug, enhancement

#58 add sign up btn
  app/views/shared/_navbar.html.erb
Labels: enhancement

#59 price is increasing in show
  app/javascript/plugins/init_Cart.js
  app/javascript/plugins/init_Modal.js
Labels: bug

#60 fixed cart addition errors
  app/javascript/plugins/init_Cart.js
  app/javascript/plugins/init_Modal.js
  app/views/cart/show.html.erb
Labels: bug

#61 second fix on shopping cart bug
  app/javascript/plugins/init_Modal.js
Labels: bug

#63 style css
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/components/_card_trip.scss
  app/assets/stylesheets/components/_cart.scss
  app/assets/stylesheets/components/_experience.scss
  app/assets/stylesheets/config/_fonts.scss
  app/assets/stylesheets/pages/_experiences.scss
  app/assets/stylesheets/pages/_index.scss
  app/assets/stylesheets/pages/_login.scss
  app/assets/stylesheets/pages/_new_review.scss
  app/assets/stylesheets/pages/favorites.scss
  app/views/cart/show.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/experiences/filter.html.erb
  app/views/experiences/index.html.erb
  app/views/experiences/results.html.erb
  app/views/experiences/show.html.erb
  app/views/favorites/index.html.erb
  app/views/reviews/edit.html.erb
  app/views/reviews/new.html.erb
Labels: enhancement

#64 Fix payments
  app/controllers/orders_controller.rb
  app/javascript/plugins/init_Cart.js
  app/models/order.rb
  app/views/cart/show.html.erb
  app/views/orders/show.html.erb
  app/views/payments/new.html.erb
  config/environments/development.rb
  db/migrate/20210920062835_add_experience_array_to_orders.rb
  db/migrate/20210920063807_remove_experiences_from_orders.rb
  db/schema.rb
Labels: enhancement

#67 final_push
  app/assets/stylesheets/components/_button.scss
  app/views/cart/show.html.erb
  app/views/experiences/filter.html.erb
  app/views/experiences/index.html.erb
  app/views/experiences/results.html.erb
  app/views/experiences/sample.html.erb
  app/views/pages/home.html.erb
  db/schema.rb
Labels: enhancement
